# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches: 
    - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: slim71
          template: classic
          config_timezone: Europe/Rome
          # What to do at each run
          output_action: commit
          committer_branch: metrics
          committer_message: "Updating metrics renders"
          # Rendering is subject to external factors and can fail occasionally
          retries: 3
          retries_delay: 300
          # Output action is also subject to GitHub API rate-limiting and overall health status and can fail occasionally
          retries_output_action: 5
          retries_delay_output_action: 120
          # Base content to show
          base: header, activity, community, repositories, metadata
          # Include forks
          repositories_forks: true
